development:
  username: postgres
  password: postgres
  adapter: postgresql
  database: montevideodetodos_development
  pool: 5

test:
  username: postgres
  password: postgres
  adapter: postgresql
  database: montevideodetodos_test
  pool: 5

production:
  username: postgres
  password: postgres
  adapter: postgresql
  database: montevideodetodos_production
  pool: 5
